<a href="https://colab.research.google.com/github/Veroberg/Calculadora-aluguel/blob/main/imovel_aluguel_implantar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pickle
import numpy as np
reg = pickle.load(open('rf_regressor_gridsearch.pkl', 'rb'))

In [3]:
n_quartos = input('numero de quartos')
area = input('area')
zona = input('zona')

zona_to_onehot = {'leste': np.array([1, 0, 0, 0]),
                  'norte': np.array([0, 1, 0, 0]),
                  'oeste': np.array([0, 0, 1, 0]),
                  'sul'  : np.array([0, 0, 0, 1])
                  }

n_quartos_log = np.log1p(int(n_quartos))
area_log = np.log1p(float(area))
zona_onehot = zona_to_onehot[zona]           

numero de quartos2
area90
zonasul


In [4]:
zona_onehot

array([0, 0, 0, 1])

In [5]:
n_quartos_log

1.0986122886681096

In [6]:
area_log

4.51085950651685

In [7]:
np.expm1(reg.predict([[1, 0, 0, 0, np.log1p(2), np.log1p(80)]]))

array([1496.98834649])

In [8]:
np.expm1(reg.predict([np.r_[zona_onehot, n_quartos_log, area_log]]))

array([1964.08609677])

In [9]:
ls

 app.py.txt  'modelo (4).pkl'      rf_regressor_gridsearch.pkl
 DS_Store    'regressor (1).pkl'   sample_data/


In [10]:
cd flask101

[Errno 2] No such file or directory: 'flask101'
/content


In [11]:
ls

 app.py.txt  'modelo (4).pkl'      rf_regressor_gridsearch.pkl
 DS_Store    'regressor (1).pkl'   sample_data/


In [12]:
from flask import Flask, render_template

In [13]:
Flask?

In [14]:
__name__

'__main__'

In [15]:
app = Flask(__name__)

In [16]:
app?

In [17]:
app.route?

In [18]:
def index():
    return render_template('primeiro_app.html')

In [19]:
@app.route('/')
def index():
    return render_template('primeiro_app.html')

In [20]:
app.run()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)


In [21]:
ls

 app.py.txt  'modelo (4).pkl'      rf_regressor_gridsearch.pkl
 DS_Store    'regressor (1).pkl'   sample_data/


In [22]:
from flask import request

In [23]:
app = Flask(__name__)

In [24]:
@app.route('/')
def index():
    return render_template('segundo_app.html')

In [25]:
@app.route('/predict', methods=['POST'])
def predict():
    form_values = [x for x in request.form.values()]
    return render_template('segundo_app.html',
            prediction_text=form_values)

In [26]:
app.run()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)


In [27]:
segundo_app = """
<!doctype html>
<html>
	<head>
		<title>Primeiro App</title>
	</head>
	<body>
		<div>Ola, este é o meu segundo app em Flask</div>
		<form action="{{ url_for('predict')}}" method="post">
        <input type="text" name="zona" placeholder="Zona" required="required" />
        <button type="submit" class="btn btn-primary btn-block btn-large">Calcular!</button>
        {{ prediction_text }}
    </form>
	</body>
</html>
"""